### ISSUE TITLE
Bug: Ambient Light Level

### ISSUE THREAD

**Issue by tomastrnka** [baboons/homebridge-electrolux-wellbeing#13]
**Describe The Bug:**

Hi, I am getting this error:

[9. 1. 2022 17:28:50] [homebridge-electrolux-wellbeing] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by tomastrnka** [comment]
HomeKit shows:
0 LUX inside the round icon
0,0001 lux under the “Current Light Level” parameter in the Light Sensor Detail

**Comment by Vooojta** [comment]
Have same issue. Have Pure A9 form friday 7th January. 

[1/13/2022, 5:02:19 PM] [ElectroluxWellbeing] Could not fetch appliances data
(node:3844) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'temp' of undefined
    at /homebridge/node_modules/homebridge-electrolux-wellbeing/src/index.ts:185:72
    at Array.map (<anonymous>)
    at ElectroluxWellbeingPlatform.updateValues (/homebridge/node_modules/homebridge-electrolux-wellbeing/src/index.ts:179:22)
    at ElectroluxWellbeingPlatform.checkAppliances (/homebridge/node_modules/homebridge-electrolux-wellbeing/src/index.ts:101:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:3844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mhuiskes** [comment]
Same issue; however I'm using the AEG XA9 air purifier. 
Electrolux Wellbeing BridgeERROR[Electrolux Wellbeing Bridge 3DB8@Airy@@Current Ambient Light Level] characteristic value expected valid finite number and received "undefined" (undefined)

Plugin Version: 0.1.0
Hoobs 4.0.110
Homebridge Version: 1.3.4
Node.js Version: 14.18.2
NPM Version:
Operating System: PI

**Comment by andreineculau** [comment]
A classic instance of "bug fixed" https://github.com/baboons/homebridge-electrolux-wellbeing/commit/3b091160b67fb62c4c2952ca61ac908ce9a0e488 but no new release.

Open a Terminal in Homebridge UI (from the "kebab" menu, top right) and in the terminal install the latest version from github:

```
cd /homebridge
npm install git+https://github.com/ysoftwareab/homebridge-electrolux-wellbeing.git#121f4b16b199dfc9c249947dbd25693542924652
```

Then restart Homebridge.

PS: it's not possible to install directly the commit in this repo, because of `.npmignore` (includes `src`) and because typescript is needed. I created a fork with the fixes. Diff https://github.com/baboons/homebridge-electrolux-wellbeing/compare/master...ysoftwareab:homebridge-electrolux-wellbeing:master

**Comment by davidjbradshaw** [comment]
As I have the AEG version, I’ve taken the fixed version, removed the light sensor, updated the dependencies and published it as [homebridge-aeg-wellbeing](https://github.com/davidjbradshaw/homebridge-aeg-wellbeing). It should work with both AEG and Electrolux versions.
