### ISSUE TITLE
Status out of sync

### ISSUE THREAD

**Issue by jkujawi** [baboons/homebridge-electrolux-wellbeing#4]
**Describe The Bug:**
I'm using the plug-in with PA91-604GY. Initially all works well, but after some time (usually 24h+) the shutdown option and the sensors stop working.

**To Reproduce:**
Try shutting down Air Purifier via Home application after some time 24h+ - it will get stuck in "Turning off..." status forever.

**Expected behavior:**
You should be able to stop managed anytime.

**Logs:**

[2/5/2021, 11:11:20 PM] [ElectroluxWellbeing] Could not fetch appliances data
(node:15642) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'temp' of undefined
    at /usr/lib/node_modules/homebridge-electrolux-wellbeing/src/index.ts:185:72
    at Array.map (<anonymous>)
    at ElectroluxWellbeingPlatform.updateValues (/usr/lib/node_modules/homebridge-electrolux-wellbeing/src/index.ts:179:22)
    at ElectroluxWellbeingPlatform.checkAppliances (/usr/lib/node_modules/homebridge-electrolux-wellbeing/src/index.ts:101:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15642) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 84932)
[2/5/2021, 11:11:30 PM] [ElectroluxWellbeing] Could not fetch appliances data
(node:15642) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'temp' of undefined
    at /usr/lib/node_modules/homebridge-electrolux-wellbeing/src/index.ts:185:72
    at Array.map (<anonymous>)
    at ElectroluxWellbeingPlatform.updateValues (/usr/lib/node_modules/homebridge-electrolux-wellbeing/src/index.ts:179:22)
    at ElectroluxWellbeingPlatform.checkAppliances (/usr/lib/node_modules/homebridge-electrolux-wellbeing/src/index.ts:101:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15642) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 84937)

**Plugin Config:**

        {
            "username": "YYYY@ZZZZ.com",
            "password": "XXXX",
            "pollTime": 10,
            "platform": "ElectroluxWellbeing"
        }

**Environment:**

* **Plugin Version**: 0.1.0
* **Homebridge Version**: v1.1.7
* **Node.js Version**: v12.19.0
* **NPM Version**: v6.14.8
* **Operating System**: raspberrypi

**Comment by holemanstristan** [comment]
Same problem with me.
